version: '3.1'
networks:
  defaulNetwork:
    driver: bridge
services:
  front:
    build:
      context: "."
      dockerfile: "./Dockerfile"
    restart: always
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - mongo
    networks:
      - defaulNetwork
    container_name: nodeapp  
  
  mongo:
    image: mongo
    restart: always
    ports:
      - "20971:27017"
    expose:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - defaulNetwork
    healthcheck:
      timeout: 10s
      interval: 10s
      retries: 5
      start_perior: 40s
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet 1

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - defaulNetwork
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example